### ISSUE TITLE
0.5.0 Roadmap

### ISSUE THREAD

**Issue by humhei** [humhei/FCSWatch#7]
- [x]  Refator to more readable codes
- [x]  Circle CI
- [x]  Multiple targetframeworks
- [x]  Deep copy dlls from obj to bin (currently has bug)
- [x]  Remove Unnessary dependecies
- [x]  Typed build system (https://github.com/humhei/FPublisher)
- [ ]  Add contribute guides

**Comment by humhei** [comment]
Almost work over the targets,
Also test it in Linux system.
